#!/bin/bash
#SBATCH --job-name=type-ratio
#SBATCH --account=_PROJECT_
#SBATCH --time=05:00:00
#SBATCH --mem-per-cpu=1G
#SBATCH --partition=small
#SBATCH --ntasks=1
#SBATCH --array=1-_TOTAL_
#SBATCH --output=/scratch/_PROJECT_/type-ratio-log/%A_%a.out
#SBATCH --error=/scratch/_PROJECT_/type-ratio-log/%A_%a.err

export OMP_NUM_THREADS=1

cd /scratch/_PROJECT_
/projappl/_PROJECT_/type-ratio-csc/type-ratio/build/type-ratio "$1" "$SLURM_ARRAY_TASK_ID" _TOTAL_
